### ISSUE TITLE
Can not download pretrained primitive fitting model

### ISSUE THREAD

**Issue by Kami-code** [Meowuu7/AutoGPart#1]
Thanks for the great project. But I can not download the pretrained model from [this link](https://drive.google.com/drive/folders/1bDF81h-ATSdiejnU888f7IihEkNhXH9r?usp=sharing), which requires permission. Can you fix it for me? By the way, I want to ask will you plan to release the dataset in future?  Does the dataset used in the primitive fitting task the same as the one in [SPFN repo](https://github.com/lingxiaoli94/SPFN) ?

**Comment by Meowuu7** [comment]
Hi, thanks for your attention to our work. I've received the permission request email. Permission to the shared folder has been updated. 
The repo is still not ready yet, and I'm trying my best to squeeze time to make it completed ASAP. The data we use for primitive fitting is not exactly the same as that of SPFN. Simply speaking, we resplit the data for generalizability test. The dataset will be released in the future. Also, there would be other things added to the repo. 
Thanks again for your attention!

**Comment by Kami-code** [comment]
Thanks a lot!
