### ISSUE TITLE
Some Inquiries about The Method

### ISSUE THREAD

**Issue by ardianumam** [Meowuu7/AutoGPart#2]
Hi,

Currently, I'm reading your paper. Thanks for making this interesting work! I have some inquiries about the method, based on my understanding from reading the paper. You may respond correct/incorrect on items below.
1. The training consists of two stages: (i) supervision search stage to train the parametric supervision model $M_T$,  then (ii) main task training stage, e.g., a segmentation task training, which integrates the AutoGpart with the already-trained $M_T$. 
2. In the supervision search stage (i), it uses reinforce method, which maximizes the reward, where the reward is inversely proportional to `generalization_score` that is defined as the performance (IoU and loss) gap between the training split and validation split. 
3. The `Greedy Supervision Selection` is only performed in the stage (ii), which samples top-k, e.g., three, supervision trees, sampled from the optimized (alread-trained) $M_T$.

Thank much!

**Comment by Meowuu7** [comment]
Hi,

Thanks for your attention to our work!
As for your questions,
1. The training process is composed of two stages, the first one is the supervision space optimization stage as you say. After that, the `Greedy Supervision Selection` process is performed to selected at most 3 features from $M_T$, which is related to your third question (please see below for details). Then, in the training stage corresponding to your stage (ii), we train the network for a certain task leveraging the above selected supervision features. 
2. Yes, the reward is set to `reward = Val_IoU - Train_IoU` serving as the metric for the generalization ability of the sampled intermediate supervision feature. 
3. The greedy supervision selection stage is performed after the first stage, saying the supervision space optimization stage. It takes top-k, e.g. 10, supervision features sampled from $M_T$ and uses the `Algorithm 3` described in the paper to select at most 3 features from the sampled k features. Selected features are then used in the following training stage. 

Please feel free to reopen the issue if you have any further question. 

Thanks again for your attention!
